homeworks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('stories/', include("stories.urls"))
]

stories/urls.py
from django.urls import path
from . import views

app_name = "stories"
urlpatterns = [
    path("", views.stories, name="stories"),
    path("<int:story_id>/", views.view_story, name="view_story"),
    path("create/", views.add_story_view, name="add_story"),
    path("<int:story_id>/update/", views.update, name="update"),
    path("<int:story_id>/delete/", views.delete, name="delete"),
    path("<int:story_id>/delete_description/<int:description_id>/", views.delete_description, name="delete_description"),
    path("<int:story_id>/edit_description/<int:description_id>/", views.edit_description, name="edit_description"),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

templates/homepage.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
Homepage
{% endblock %}

{% block content %}

<div class="container w-100 h-100 d-flex flex-column align-items-center justify-content-center">
    <div class="d-flex">
        <a href="{% url 'stories:stories' %}" type="button" class="btn btn-outline-warning me-1" role="button"
           aria-pressed="true">Bring a
            spark</a>
        <a href="{% url 'stories:add_story' %}" type="button" class="btn btn-outline-danger ms-1" role="button"
           aria-pressed="true">Tell a
            story</a>
    </div>

</div>

{% endblock %}

{% block extra_body_class %}
homepage-background
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href=
            "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<body class="d-flex flex-column min-vh-100 align-items-center {% block extra_body_class %}{% endblock %}">
<div class="page-wrapper">

    <!-- Navbar -->
    {% url 'stories:stories' as stories_url %}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark w-80">
        <div class="container nav-container d-flex align-items-center justify-content-between">
            <a class="logo-text me-3 " href="/">the storyteller</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex justify-content-between align-content-end" id="navbarCollapse">
                <div class="d-flex align-items-center ">
                    {% if not user.is_authenticated %}
                    <a href="/users/login" class="text-white me-3">Login</a>
                    <a href="/users/register" class="btn btn-outline-light">Register</a>
                    {%endif %}
                    {% if user.is_authenticated %}
                    <span class="me-3">
                        <span class="username_text opacity-50">Welcome, </span>
                        <a class="username"
                           href="{% url 'stories:stories' %}?search_by='owner'&search_text={{user.username}}">{{ user.username }}!</a>
                    </span>
                    <a href="{% url 'stories:add_story' %}"
                       type="button"
                       class="btn btn-outline-danger ms-1 me-3"
                       role="button"
                       aria-pressed="true">Tell a story</a>
                    <form action="{% url 'users:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light">Logout</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <!-- Breadcrumbs Block -->
    <div class="container mt-3">
        {% block breadcrumbs %}
        <!--        <nav aria-label="breadcrumb">-->
        <!--            <ol class="breadcrumb">-->
        <!--                <li class="breadcrumb-item"><a href="/">Home</a></li>-->
        <!--                <li class="breadcrumb-item active" aria-current="page">Current Page</li>-->
        <!--            </ol>-->
        <!--        </nav>-->
        {% endblock %}
    </div>

    <!-- Filter Block (Optional) -->
    <div class="container mt-3">
        {% block filters %}
        {% endblock %}
    </div>

    <!-- Main Content Block (Centered, 80% Width) -->
    <div class="content-wrapper">
        <div class="container main-content mt-5">
            {% block content %}
            <!-- Block for dynamic content -->
            {% endblock %}
        </div>
    </div>

    <!-- Footer Section -->
    <footer class="text-white mt-5 py-3 w-100 footer">
        <div class="container text-center ">
            <p class="mb-0">&copy; 2024 Illume Ideas. All rights reserved.</p>
        </div>
    </footer>

    {% block extra_scripts %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/your-kit-id.js" crossorigin="anonymous"></script>
</div>
</body>
</html>