homeworks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('stories/', include("stories.urls"))
]

stories/urls.py
from django.urls import path
from . import views

app_name = "stories"
urlpatterns = [
    path("", views.stories, name="stories"),
    path("<int:story_id>/", views.view_story, name="view_story"),
    path("create/", views.add_story_view, name="add_story"),
    path("<int:story_id>/update/", views.update, name="update"),
    path("<int:story_id>/delete/", views.delete, name="delete"),
    path("<int:story_id>/delete_description/<int:description_id>/", views.delete_description, name="delete_description"),
    path("<int:story_id>/edit_description/<int:description_id>/", views.edit_description, name="edit_description"),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

stories/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Story(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, related_name='stories')
    created_at = models.DateTimeField(auto_now_add=True)  # Add this field

    def __str__(self):
        return self.name


class Description(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='descriptions')
    description_text = models.TextField()
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)  # Add this field

    def __str__(self):
        return f'Description for {self.story.name} by {self.added_by.username}'

stories/forms.py
from django import forms
from .models import Story, Description, Category
from django.contrib.auth.models import User


class StoryForm(forms.ModelForm):
    new_category = forms.CharField(required=False, max_length=30)

    class Meta:
        model = Story
        fields = ['name', 'categories']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'story-title placeholder-centered', 'placeholder': 'Add story title'}),
            'categories': forms.CheckboxSelectMultiple(),
        }
        labels = {
            'name': '',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make 'categories' field optional
        self.fields['categories'].required = False
        # Add attributes for 'new_category' field
        self.fields['new_category'].widget.attrs.update({
            'class': 'minimal-textarea placeholder-centered fs-4',
            'placeholder': 'Custom category here'
        })

    def save(self, commit=True):
        # Call the parent save method to create the story object
        story = super().save(commit=False)
        new_category_name = self.cleaned_data.get('new_category')

        if commit:
            story.save()
            # Handle the new category if provided
            if new_category_name:
                category, created = Category.objects.get_or_create(name=new_category_name)
                story.categories.add(category)
                self.save_m2m()
        return story


class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ('description_text',)
        widgets = {
            'description_text': forms.Textarea(
                attrs={'class': 'minimal-textarea story-container placeholder-centered',
                       'id': 'description_text_input',
                       'placeholder': 'Continue story here'})
        }
        labels = {
            'description_text': '',
        }

stories/views.py
import json

from django.db.models import Prefetch
from django.shortcuts import render, redirect
from .forms import StoryForm, DescriptionForm
from .models import Story, Description, Category
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required


def stories(request):
    search_by = request.GET.get('search_by')
    search_text = request.GET.get('search_text')
    if search_by and search_text:
        match search_by:
            case 'owner':
                db_stories = Story.objects.select_related('owner').prefetch_related(
                    'categories',
                    'descriptions__added_by'
                ).filter(owner__username__icontains=search_text).order_by('-created_at')
            case 'description':
                db_stories = Story.objects.select_related('owner').prefetch_related(
                    'categories',
                    'descriptions__added_by'
                ).filter(descriptions__description_text__icontains=search_text).order_by('-created_at')
            case 'category':
                db_stories = Story.objects.select_related('owner').prefetch_related(
                    'categories', 'descriptions__added_by'
                ).filter(categories__name__icontains=search_text).order_by('-created_at')
                # For multiple categories:
                # category_list = search_text.split(',')  # Split search text by commas to get list of categories
                # db_stories = Story.objects.select_related('owner').prefetch_related(
                #     'categories', 'descriptions__added_by'
                # ).filter(categories__name__in=category_list).distinct().order_by('-id')
            case _:
                db_stories = Story.objects.select_related('owner').prefetch_related(
                    'categories',
                    Prefetch('descriptions', queryset=Description.objects.select_related('added_by').order_by('created_at'))
                ).order_by('-created_at')
    else:
        db_stories = Story.objects.select_related('owner').prefetch_related(
            'categories',
            Prefetch('descriptions', queryset=Description.objects.select_related('added_by').order_by('created_at'))
        ).order_by('-created_at')
    total_stories = db_stories.count()
    return render(request, 'stories/stories.html', {
        'stories': db_stories,
        'total_stories': total_stories,
        'search_by': search_by,
        'search_text': search_text
    })


@login_required(login_url="/users/login")
def add_story_view(request):
    if request.method == 'POST':
        story_form = StoryForm(request.POST)
        description_form = DescriptionForm(request.POST)
        if story_form.is_valid() and description_form.is_valid():
            story = story_form.save(commit=False)
            story.owner = request.user
            story.save()

            for category in story_form.cleaned_data['categories']:
                print(category)
                story.categories.add(category)

            new_category_name = story_form.cleaned_data.get('new_category')
            if new_category_name:
                print(story_form.cleaned_data['new_category'])
                category, created = Category.objects.get_or_create(name=story_form.cleaned_data['new_category'])
                print(category, created)
                print(created)
                story.categories.add(category)

            description = description_form.save(commit=False)
            description.story = story
            description.added_by = request.user
            description.save()

            return redirect('stories:view_story', story_id=story.id)
    else:
        story_form = StoryForm()
        description_form = DescriptionForm()

    return render(request, 'stories/add_story.html', {'story_form': story_form, 'description_form': description_form})


def view_story(request, story_id):
    # story = Story.objects.select_related('owner').prefetch_related(
    #     'categories', 'descriptions__added_by'
    # ).get(id=story_id)
    story = get_object_or_404(Story, id=story_id)
    descriptions = story.descriptions.all().order_by('created_at')
    categories = story.categories.all()
    if request.method == 'POST':
        form = DescriptionForm(request.POST)
        if form.is_valid():
            description = form.save(commit=False)
            description.story = story
            description.added_by = request.user
            description.save()
            return redirect('stories:view_story', story_id=story_id)
    else:
        form = DescriptionForm()

    return render(request, 'stories/view_story.html', {
        'story': story,
        'descriptions': descriptions,
        'categories': categories,
        'form': form
    })


# delete Story
def delete(request):
    return render(request, 'stories/stories.html')


def update(request):
    return render(request, 'stories/stories.html')


@login_required
def edit_description(request, story_id, description_id):
    story = get_object_or_404(Story, id=story_id)
    description = get_object_or_404(Description, id=description_id, story_id=story_id)

    if description.story != story:
        return redirect('stories:view_story', story_id=story_id)

    if request.method == 'POST' and request.user == description.added_by:
        new_text = request.POST.get('description_text')
        description.description_text = new_text
        description.save()
        return redirect('stories:view_story', story_id=story_id)
    return redirect('stories:view_story', story_id=story_id)


def delete_description(request, story_id, description_id):
    description = get_object_or_404(Description, id=description_id)
    if description:
        description.delete()
        return redirect('stories:view_story', story_id=story_id)
    return redirect('stories:view_story', story_id=story_id)

stories/templates/stories/add_story.html
{% extends 'layout.html' %}

{% block title %}
User Login
{% endblock %}

{% block content %}
<div class='view-story-main-container'>
    <a href="{% url 'stories:stories' %}"
       class="mt-10 link-light
   link-offset-2
   link-underline-opacity-25
   link-underline-opacity-100-hover">
        All stories
    </a>
    <form method="post">
        {% csrf_token %}
        <div class="d-flex align-items-center flex-column">
            <div class="form-group">
                {{ story_form.name }}
            </div>
            <div class="form-group">
                <div class="container mt-0 d-flex flex-column align-items-center">
                    <div class="mb-3">
                        {{ story_form.new_category}}
                    </div>
                    <div class="row">
                        {% for category in story_form.categories %}
                        <div class="col-4">
                            <span>{{ category.tag }} </span>
                            <span>{{ category.choice_label }}</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-dark mt-3">Save</button>

            <hr class="dotted mt-3 w-50">

            <div class="d-flex flex-column align-items-center">
                {{ description_form }}
            </div>
        </div>
    </form>
</div>
{% endblock %}

stories/templates/stories/stories.html
{% extends 'layout.html' %}

{% block title %}
Illums
{% endblock %}

{% block content %}

<div class="stories-main-container">
    <div class="d-flex align-items-center justify-content-between mb-5">
        <div>{{total_stories}}
            {% if total_stories == 1 %}
            Story
            {% else %}
            Stories
            {% endif %}
        </div>

        {% if search_by %}
        <div>
            Searched by:
            <div class="btn btn-outline-light opacity-75 category-btn ms-2 text-hover-dark">
                <span class="px-2">{{ search_text }}</span>
                <a class="text-hover-dark" href="{% url 'stories:stories' %}"><i class="fa fa-times mx-1"
                                                                                 aria-hidden="true"></i></a></div>
        </div>
        {% endif %}
    </div>

    {% for story in stories %}
    <div class="d-flex flex-column align-items-center">

        <div class="d-flex flex-column">
            <h2 class="story-title m-0">{{ story.name }}</h2>
            <div class="fs-7 text text-center author-stories mt-1">
                <a href="{% url 'stories:stories' %}?search_by='owner'&search_text={{story.owner.username}}" class="link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                    by <span class="fs-5 text">{{ story.owner.username }}</span>
                </a>
            </div>
        </div>

        <p class="text-center mt-3">
            {% for category in story.categories.all %}
            <a href="{% url 'stories:stories' %}?search_by=category&search_text={{ category.name }}"
               class="btn btn-outline-light opacity-75 category-btn ">
                {{category}}</a>
            {% endfor %}
        </p>
        {% for paraghraph in story.descriptions.all|slice:":1" %}
        <p class="story-content-list mt-3">{{ paraghraph.description_text|truncatechars:1000 }}</p>
        {% endfor %}
        <a class="link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover text-center w-50 opacity-75"
           href="{% url 'stories:view_story' story.id %}">read more</a>
        <hr class="dotted mt-1 w-50">

    </div>

    {% endfor %}
</div>
{% endblock %}

{% block extra_body_class %}
homepage-background
{% endblock %}


{% block extra_scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('autoFocusTextarea').focus();
    });
</script>
{% endblock %}

stories/templates/stories/view_story.html
{% extends 'layout.html' %}

{% block title %}
User Login
{% endblock %}

{% block content %}
<div class='view-story-main-container'>
    <a href="{% url 'stories:stories' %}"
       class="mt-10 link-light
   link-offset-2
   link-underline-opacity-25
   link-underline-opacity-100-hover">
        All stories
    </a>
    <div class="d-flex flex-column align-items-center">
        <div class="story-title mt-5 pb-0">{{ story.name }}</div>
        <div class="text-center author-stories mt-1">
            <a class="link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
               href="{% url 'stories:stories'%}?search_by=owner&search_text={{ story.owner.username }}">
                by <span class="fs-5 text">{{ story.owner.username }}</span>
            </a>
        </div>
        <p class="text-center mt-3">
            {% for category in categories %}
            <a href="{% url 'stories:stories' %}?search_by=category&search_text={{ category.name }}" class="text-decoration-none btn btn-outline-light opacity-75 category-btn ">
                {{category}}</a>
            {% endfor %}
        </p>

        <div class="story-content flex flex-column mt-5">
            {% for description in descriptions %}
            <div class="description-item">
                <p class="description-text" data-description-id="{{ description.id }}">{{ description.description_text }}
                     <span class="me-3 author"> - by <a href="{% url 'stories:stories' %}?search_by=owner&search_text={{ description.added_by.username }}" class="cursor-pointer author"> {{ description.added_by.username }}</a></span>
                    {% if user.username == description.added_by.username %}
                    <i class="fa fa-pencil-square opacity-75 btn p-0 edit-btn" aria-hidden="true"
                       data-description-id="{{description.id}}"></i>
                    <a href="{% url 'stories:delete_description' story.id description.id %}" title="Delete Description"
                       onclick="return confirm('Are you sure you want to delete this description?');">
                        <i class="fa fa-minus-square opacity-75 btn p-0" aria-hidden="true"></i>
                    </a>
                    {% endif %}
                </p>
                <form method="POST" action="{% url 'stories:edit_description' story.id description.id %}"
                      class="edit-form hidden mb-3 d-flex flex-column align-items-center"
                      data-description-id="{{description.id}}">
                    {% csrf_token %}
                    <textarea name="description_text" class="form-control edit_element hidden minimal-textarea edit-story-container placeholder-centered"
                           data-description-id="{{description.id}}">{{description.description_text}}</textarea>
                    <hr class="hidden edit_element dotted mt-3 w-50" data-description-id="{{description.id}}">
                    <button type="submit" class="hidden edit_element btn btn-dark mt-3" data-description-id="{{description.id}}">Save</button>
                </form>
            </div>
            {% endfor %}
        </div>
        <hr class="dotted mt-3">
        <form method="POST">
            <div class="d-flex flex-column align-items-center">
                <button type="submit"
                        id="save-new-button"
                        class="save-new-button hidden btn btn-dark mt-3">Save</button>
                <hr class="dotted mt-3 w-50">
                {% csrf_token %}
                {{ form }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script>
function autoResize(textarea) {
    textarea.style.height = 'auto'; // Reset height
    textarea.style.height = textarea.scrollHeight + 'px'; // Set new height
}
</script>
<script>
const descriptionInput = document.getElementById('description_text_input');
console.log(descriptionInput)
const saveNewButton = document.getElementById('save-new-button');
descriptionInput.addEventListener('input', () => {
    console.log(descriptionInput.value)
    saveNewButton.classList.toggle("hidden", !descriptionInput.value.trim());
    console.log(saveNewButton.classList)
});
document.addEventListener('DOMContentLoaded', function() {
document.querySelectorAll('.edit-btn').forEach(button => {
    button.addEventListener('click', function() {
        const descriptionId = this.getAttribute('data-description-id');
        const descriptionText = document.querySelector(`.description-text[data-description-id="${descriptionId}"]`);
        const editForm = document.querySelector(`.edit-form[data-description-id="${descriptionId}"]`);
        const editElements = document.querySelectorAll(`.edit_element[data-description-id="${descriptionId}"]`);

        if (descriptionText && editForm) {
            editForm.classList.toggle('hidden');
            editElements.forEach(element => element.classList.toggle('hidden'));
            console.log(editElements)
            descriptionText.style.display = editForm.classList.contains('hidden') ? 'block' : 'none';
            console.log(editForm.style)
            if (editForm.style.display !== 'none') {
                    const textarea = editForm.querySelector('textarea');
                    autoResize(textarea);
                }
        } else {
            console.error("Elements not found for ID:", descriptionId);
        }
    });
});
});
</script>
{% endblock %}